Update Inst1

diff --git a/Inst1 b/Inst1
--- a/Inst1
+++ b/Inst1
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 set -uo pipefail
-
+trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
 
 #ask user if checks completed
 echo -n "Were Checks Completed: "
